// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DcodePe.Catering.Domain.Entities;

public partial class PaginaEntity
{
    public int PaginaID { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }
    public string Url { get; set; }
    public string Icono { get; set; }

    public string UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string UsuarioEliminacion { get; set; }

    public DateTime? FechaEliminacion { get; set; }

    public bool? Estado { get; set; }

    public virtual ICollection<PermisoEntity> Permiso { get; set; } = new List<PermisoEntity>();
}