// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DcodePe.Catering.Domain.Entities;

public partial class PermisoEntity
{
    public int PermisoID { get; set; }

    public int RolID { get; set; }

    public int PaginaID { get; set; }

    public bool? PuedeVer { get; set; }

    public bool? PuedeCrear { get; set; }

    public bool? PuedeEditar { get; set; }

    public bool? PuedeEliminar { get; set; }

    public string UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string UsuarioEliminacion { get; set; }

    public DateTime? FechaEliminacion { get; set; }

    public bool? Estado { get; set; }

    public virtual PaginaEntity Pagina { get; set; }

    public virtual RolEntity Rol { get; set; }
}