// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DcodePe.Catering.Domain.Entities;

public partial class UsuarioEntity
{
    public int UsuarioID { get; set; }

    public string Nombre { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int RolID { get; set; }

    public string UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string UsuarioEliminacion { get; set; }

    public DateTime? FechaEliminacion { get; set; }

    public bool? Estado { get; set; }

    public virtual ICollection<BlogEntity> Blog { get; set; } = new List<BlogEntity>();

    public virtual RolEntity Rol { get; set; }
}