// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DcodePe.Catering.Domain.Entities;

public partial class LogAuditoriaEntity
{
    public int LogID { get; set; }

    public string Acción { get; set; }

    public string TablaAfectada { get; set; }

    public int RegistroID { get; set; }

    public string Usuario { get; set; }

    public DateTime? Fecha { get; set; }
}