// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DcodePe.Catering.Domain.Entities;

public partial class LogErroresEntity
{
    public int ErrorID { get; set; }

    public string Mensaje { get; set; }

    public string StackTrace { get; set; }

    public string Usuario { get; set; }

    public DateTime? Fecha { get; set; }
}