// <auto-generated />
using System;
using DcodePe.Catering.Persistence.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DcodePe.Catering.Persistence.Migrations
{
    [DbContext(typeof(DataBaseService))]
    [Migration("20250304024939_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.BlogEntity", b =>
                {
                    b.Property<int>("BlogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogID"));

                    b.Property<int>("AutorID")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaPublicación")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioEliminacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BlogID");

                    b.HasIndex("AutorID");

                    b.ToTable("Blog", (string)null);
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.Booking.BookingEntity", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.CotizacionEntity", b =>
                {
                    b.Property<int>("CotizacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CotizacionID"));

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("EstadoCotizacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("NumeroInvitados")
                        .HasColumnType("int");

                    b.Property<decimal>("PresupuestoPorPersona")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CotizacionID")
                        .HasName("PK__Cotizaci__30443A5921D82495");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Cotizacion", (string)null);
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.CotizacionProductoEntity", b =>
                {
                    b.Property<int>("CotizacionID")
                        .HasColumnType("int");

                    b.Property<int>("ProductoID")
                        .HasColumnType("int");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CotizacionID", "ProductoID")
                        .HasName("PK__Cotizaci__1A0730B1F102918F");

                    b.HasIndex("ProductoID");

                    b.ToTable("CotizacionProducto", (string)null);
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.CotizacionServicioEntity", b =>
                {
                    b.Property<int>("CotizacionID")
                        .HasColumnType("int");

                    b.Property<int>("ServicioID")
                        .HasColumnType("int");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CotizacionID", "ServicioID")
                        .HasName("PK__Cotizaci__0D1ED49B07A984DD");

                    b.HasIndex("ServicioID");

                    b.ToTable("CotizacionServicio", (string)null);
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.Customer.CustomerEntity", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.EventoEntity", b =>
                {
                    b.Property<int>("EventoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventoID"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("EstadoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("LocalID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EventoID")
                        .HasName("PK__Evento__1EEB5901FC5279F4");

                    b.HasIndex("LocalID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Evento", (string)null);
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.LocalEntity", b =>
                {
                    b.Property<int>("LocalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalID"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Fotos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TerminosCondiciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LocalID")
                        .HasName("PK__Local__499359DBAF7800EF");

                    b.ToTable("Local", (string)null);
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.LogAuditoriaEntity", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("Acción")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("RegistroID")
                        .HasColumnType("int");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LogID")
                        .HasName("PK__LogAudit__5E5499A8B9526321");

                    b.ToTable("LogAuditoria", "Auditoria");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.LogErroresEntity", b =>
                {
                    b.Property<int>("ErrorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ErrorID"));

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ErrorID")
                        .HasName("PK__LogError__358565CA1E55C3E9");

                    b.ToTable("LogErrores", "Auditoria");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.PaginaEntity", b =>
                {
                    b.Property<int>("PaginaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaginaID"));

                    b.Property<string>("Descripción")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaginaID")
                        .HasName("PK__Pagina__31EFFA4D5845C0D1");

                    b.ToTable("Pagina", (string)null);
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.PaqueteEntity", b =>
                {
                    b.Property<int>("PaqueteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaqueteID"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaqueteID")
                        .HasName("PK__Paquete__7B9F2DD2F0612323");

                    b.ToTable("Paquete", (string)null);
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.PaqueteProductoEntity", b =>
                {
                    b.Property<int>("PaqueteID")
                        .HasColumnType("int");

                    b.Property<int>("ProductoID")
                        .HasColumnType("int");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaqueteID", "ProductoID")
                        .HasName("PK__PaqueteP__51DC273AB8D4D98B");

                    b.HasIndex("ProductoID");

                    b.ToTable("PaqueteProducto", (string)null);
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.PaqueteServicioEntity", b =>
                {
                    b.Property<int>("PaqueteID")
                        .HasColumnType("int");

                    b.Property<int>("ServicioID")
                        .HasColumnType("int");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaqueteID", "ServicioID")
                        .HasName("PK__PaqueteS__46C5C310A219C7EF");

                    b.HasIndex("ServicioID");

                    b.ToTable("PaqueteServicio", (string)null);
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.PermisoEntity", b =>
                {
                    b.Property<int>("PermisoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermisoID"));

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<int>("PaginaID")
                        .HasColumnType("int");

                    b.Property<bool?>("PuedeCrear")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("PuedeEditar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("PuedeEliminar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("PuedeVer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PermisoID")
                        .HasName("PK__Permiso__96E0C70367B46FD4");

                    b.HasIndex("PaginaID");

                    b.HasIndex("RolID");

                    b.ToTable("Permiso", (string)null);
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.ProductoEntity", b =>
                {
                    b.Property<int>("ProductoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoID"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductoID")
                        .HasName("PK__Producto__A430AE838BF44EEC");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.RolEntity", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolID"));

                    b.Property<string>("Descripción")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RolID")
                        .HasName("PK__Rol__F92302D107BDE9CD");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.ServicioAdicionalEntity", b =>
                {
                    b.Property<int>("ServicioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicioID"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ServicioID")
                        .HasName("PK__Servicio__D5AEEC2230B36B62");

                    b.ToTable("ServicioAdicional", (string)null);
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.User.UserEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.UsuarioEntity", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UsuarioID")
                        .HasName("PK__Usuario__2B3DE7985AB70077");

                    b.HasIndex("RolID");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuario__A9D1053408714BD2")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.BlogEntity", b =>
                {
                    b.HasOne("DcodePe.Catering.Domain.Entities.UsuarioEntity", "Autor")
                        .WithMany("Blog")
                        .HasForeignKey("AutorID")
                        .IsRequired()
                        .HasConstraintName("FK__Blog__AutorID__6754599E");

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.Booking.BookingEntity", b =>
                {
                    b.HasOne("DcodePe.Catering.Domain.Entities.Customer.CustomerEntity", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DcodePe.Catering.Domain.Entities.User.UserEntity", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.CotizacionEntity", b =>
                {
                    b.HasOne("DcodePe.Catering.Domain.Entities.UsuarioEntity", "Usuario")
                        .WithMany("Cotizacion")
                        .HasForeignKey("UsuarioID")
                        .IsRequired()
                        .HasConstraintName("FK__Cotizacio__Usuar__6E01572D");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.CotizacionProductoEntity", b =>
                {
                    b.HasOne("DcodePe.Catering.Domain.Entities.CotizacionEntity", "Cotizacion")
                        .WithMany("CotizacionProducto")
                        .HasForeignKey("CotizacionID")
                        .IsRequired()
                        .HasConstraintName("FK__Cotizacio__Cotiz__787EE5A0");

                    b.HasOne("DcodePe.Catering.Domain.Entities.ProductoEntity", "Producto")
                        .WithMany("CotizacionProducto")
                        .HasForeignKey("ProductoID")
                        .IsRequired()
                        .HasConstraintName("FK__Cotizacio__Produ__797309D9");

                    b.Navigation("Cotizacion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.CotizacionServicioEntity", b =>
                {
                    b.HasOne("DcodePe.Catering.Domain.Entities.CotizacionEntity", "Cotizacion")
                        .WithMany("CotizacionServicio")
                        .HasForeignKey("CotizacionID")
                        .IsRequired()
                        .HasConstraintName("FK__Cotizacio__Cotiz__72C60C4A");

                    b.HasOne("DcodePe.Catering.Domain.Entities.ServicioAdicionalEntity", "Servicio")
                        .WithMany("CotizacionServicio")
                        .HasForeignKey("ServicioID")
                        .IsRequired()
                        .HasConstraintName("FK__Cotizacio__Servi__73BA3083");

                    b.Navigation("Cotizacion");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.EventoEntity", b =>
                {
                    b.HasOne("DcodePe.Catering.Domain.Entities.LocalEntity", "Local")
                        .WithMany("Evento")
                        .HasForeignKey("LocalID")
                        .IsRequired()
                        .HasConstraintName("FK__Evento__LocalID__5CD6CB2B");

                    b.HasOne("DcodePe.Catering.Domain.Entities.UsuarioEntity", "Usuario")
                        .WithMany("Evento")
                        .HasForeignKey("UsuarioID")
                        .IsRequired()
                        .HasConstraintName("FK__Evento__UsuarioI__5DCAEF64");

                    b.Navigation("Local");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.PaqueteProductoEntity", b =>
                {
                    b.HasOne("DcodePe.Catering.Domain.Entities.PaqueteEntity", "Paquete")
                        .WithMany("PaqueteProducto")
                        .HasForeignKey("PaqueteID")
                        .IsRequired()
                        .HasConstraintName("FK__PaquetePr__Paque__7E37BEF6");

                    b.HasOne("DcodePe.Catering.Domain.Entities.ProductoEntity", "Producto")
                        .WithMany("PaqueteProducto")
                        .HasForeignKey("ProductoID")
                        .IsRequired()
                        .HasConstraintName("FK__PaquetePr__Produ__7F2BE32F");

                    b.Navigation("Paquete");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.PaqueteServicioEntity", b =>
                {
                    b.HasOne("DcodePe.Catering.Domain.Entities.PaqueteEntity", "Paquete")
                        .WithMany("PaqueteServicio")
                        .HasForeignKey("PaqueteID")
                        .IsRequired()
                        .HasConstraintName("FK__PaqueteSe__Paque__03F0984C");

                    b.HasOne("DcodePe.Catering.Domain.Entities.ServicioAdicionalEntity", "Servicio")
                        .WithMany("PaqueteServicio")
                        .HasForeignKey("ServicioID")
                        .IsRequired()
                        .HasConstraintName("FK__PaqueteSe__Servi__04E4BC85");

                    b.Navigation("Paquete");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.PermisoEntity", b =>
                {
                    b.HasOne("DcodePe.Catering.Domain.Entities.PaginaEntity", "Pagina")
                        .WithMany("Permiso")
                        .HasForeignKey("PaginaID")
                        .IsRequired()
                        .HasConstraintName("FK__Permiso__PaginaI__45F365D3");

                    b.HasOne("DcodePe.Catering.Domain.Entities.RolEntity", "Rol")
                        .WithMany("Permiso")
                        .HasForeignKey("RolID")
                        .IsRequired()
                        .HasConstraintName("FK__Permiso__RolID__44FF419A");

                    b.Navigation("Pagina");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.UsuarioEntity", b =>
                {
                    b.HasOne("DcodePe.Catering.Domain.Entities.RolEntity", "Rol")
                        .WithMany("Usuario")
                        .HasForeignKey("RolID")
                        .IsRequired()
                        .HasConstraintName("FK__Usuario__RolID__4BAC3F29");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.CotizacionEntity", b =>
                {
                    b.Navigation("CotizacionProducto");

                    b.Navigation("CotizacionServicio");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.Customer.CustomerEntity", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.LocalEntity", b =>
                {
                    b.Navigation("Evento");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.PaginaEntity", b =>
                {
                    b.Navigation("Permiso");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.PaqueteEntity", b =>
                {
                    b.Navigation("PaqueteProducto");

                    b.Navigation("PaqueteServicio");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.ProductoEntity", b =>
                {
                    b.Navigation("CotizacionProducto");

                    b.Navigation("PaqueteProducto");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.RolEntity", b =>
                {
                    b.Navigation("Permiso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.ServicioAdicionalEntity", b =>
                {
                    b.Navigation("CotizacionServicio");

                    b.Navigation("PaqueteServicio");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.User.UserEntity", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("DcodePe.Catering.Domain.Entities.UsuarioEntity", b =>
                {
                    b.Navigation("Blog");

                    b.Navigation("Cotizacion");

                    b.Navigation("Evento");
                });
#pragma warning restore 612, 618
        }
    }
}
