// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DcodePe.Catering.Domain.Entities.Base;
using DcodePe.Catering.Domain.Entities.Clientes;
using System.Runtime.ConstrainedExecution;

namespace DcodePe.Catering.Domain.Entities;

public partial class CotizacionEntity : BaseEntity
{
    public int CotizacionID { get; set; }

    public int ClienteID { get; set; }

    public int LocalID { get; set; }

    public int? EventoID { get; set; }

    public DateTime? FechaTentativa { get; set; }
    public DateTime? FechaTentativaOpcional { get; set; }

    public DateTime? FechaContacto { get; set; }
    public TimeOnly? HoraContacto { get; set; }

    public int NumeroInvitados { get; set; }
    
    public decimal CostoDePersonal { get; set; }
    public decimal Garantia { get; set; }
    
    // PASO 1: Tarifa base por persona (productos + personal)
    public decimal TarifaMenuPorInvitado { get; set; } // Antes: PresupuestoPorPersona
    
    // PASO 2: Subtotal del menú (TarifaMenuPorInvitado * NumeroInvitados)
    public decimal SubtotalMenu { get; set; } // Antes: PresupuestoInvitados
    
    // PASO 3: Total con venue, garantía y servicios adicionales
    public decimal TotalEvento { get; set; } // Antes: CalculoTotal
    
    // PASO 4: Precio por invitado antes de descuento
    public decimal PrecioPorCubierto { get; set; } // Antes: PrecioPorPersona
    
    // PASO 5: Precio por invitado después del descuento
    public decimal PrecioPorCubiertoConDescuento { get; set; } // Antes: DescuentoPorPersona
    
    // PASO 6: Total final de la cotización
    public decimal TotalCotizacion { get; set; } // Antes: CostoTotal

    public string Observacion { get; set; }

    public string EstadoCotizacion { get; set; }


    public virtual ICollection<CotizacionProductoEntity> CotizacionProducto { get; set; } = new List<CotizacionProductoEntity>();

    public virtual ICollection<CotizacionServicioEntity> CotizacionServicio { get; set; } = new List<CotizacionServicioEntity>();

    public virtual ICollection<CotizacionPaqueteEntity> CotizacionPaquete { get; set; } = new List<CotizacionPaqueteEntity>();

    public virtual ClienteEntity Cliente { get; set; }

    public virtual LocalEntity Local { get; set; }

    public virtual EventoEntity Evento { get; set; }
}
