// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DcodePe.Catering.Domain.Entities;

public partial class EventoEntity
{
    public int EventoID { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }
    
    /// <summary>
    /// URL de la foto del evento
    /// </summary>
    public string Fotos { get; set; }

    public string EstadoEvento { get; set; }

    public string UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string UsuarioEliminacion { get; set; }

    public DateTime? FechaEliminacion { get; set; }

    public bool? Estado { get; set; }

    public virtual ICollection<CotizacionEntity> Cotizaciones { get; set; } = new List<CotizacionEntity>();
}
