// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace DcodePe.Catering.Domain.Entities;

public partial class PaqueteServicioEntity
{
    public int PaqueteID { get; set; }

    public int ServicioID { get; set; }

    public int Cantidad { get; set; }

    public string UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string UsuarioEliminacion { get; set; }

    public DateTime? FechaEliminacion { get; set; }

    public bool? Estado { get; set; }

    public virtual PaqueteEntity Paquete { get; set; }

    public virtual ServicioAdicionalEntity Servicio { get; set; }
}