// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace DcodePe.Catering.Domain.Entities;

public partial class PaqueteEntity
{
    public int PaqueteID { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public decimal PrecioTotal { get; set; }

    public string UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string UsuarioEliminacion { get; set; }

    public DateTime? FechaEliminacion { get; set; }

    public bool? Estado { get; set; }

    public virtual ICollection<PaqueteProductoEntity> PaqueteProducto { get; set; } = new List<PaqueteProductoEntity>();

    public virtual ICollection<PaqueteServicioEntity> PaqueteServicio { get; set; } = new List<PaqueteServicioEntity>();

    public virtual ICollection<CotizacionPaqueteEntity> CotizacionPaquete { get; set; } = new List<CotizacionPaqueteEntity>();
}