// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DcodePe.Catering.Domain.Entities.Base;
using System.ComponentModel.DataAnnotations.Schema;

namespace DcodePe.Catering.Domain.Entities;

public partial class ProductoEntity : BaseEntity
{
    public int ProductoID { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public decimal Precio { get; set; }
    public decimal PrecioCosto { get; set; }
    public string Fotos { get; set; }

    /// <summary>
    /// Foreign Key a CategoriaEntity
    /// </summary>
    public int CategoriaID { get; set; }

    /// <summary>
    /// Navegación a la categoría del producto
    /// </summary>
    public virtual CategoriaEntity Categoria { get; set; }

    // Los campos de auditoría ahora se heredan de BaseEntity:
    // - UsuarioCreacion
    // - FechaCreacion
    // - UsuarioModificacion
    // - FechaModificacion
    // - UsuarioEliminacion
    // - FechaEliminacion
    // - Estado

    public virtual ICollection<CotizacionProductoEntity> CotizacionProducto { get; set; } = new List<CotizacionProductoEntity>();

    public virtual ICollection<PaqueteProductoEntity> PaqueteProducto { get; set; } = new List<PaqueteProductoEntity>();

    [NotMapped]
    public ICollection<string> FotosUrls
    {
        get => string.IsNullOrEmpty(Fotos)
            ? new List<string>()
            : Fotos.Split(';', StringSplitOptions.RemoveEmptyEntries).ToList();
        set => Fotos = value != null && value.Any()
            ? string.Join(";", value)
            : null;
    }
}