// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations.Schema;

namespace DcodePe.Catering.Domain.Entities;

public partial class ServicioAdicionalEntity
{
    public int ServicioID { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public decimal Precio { get; set; }

    /// <summary>Mínimo de invitados requeridos para contratar este servicio.</summary>
    public int CantidadMinima { get; set; } = 1;

    public string Fotos { get; set; }

    public string UsuarioCreacion { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string UsuarioEliminacion { get; set; }

    public DateTime? FechaEliminacion { get; set; }

    public bool? Estado { get; set; }

    public virtual ICollection<CotizacionServicioEntity> CotizacionServicio { get; set; } = new List<CotizacionServicioEntity>();

    public virtual ICollection<PaqueteServicioEntity> PaqueteServicio { get; set; } = new List<PaqueteServicioEntity>();

    [NotMapped]
    public ICollection<string> FotosUrls
    {
        get => string.IsNullOrEmpty(Fotos)
            ? new List<string>()
            : Fotos.Split(';', StringSplitOptions.RemoveEmptyEntries).ToList();
        set => Fotos = value != null && value.Any()
            ? string.Join(";", value)
            : null;
    }
}